<a id='Q0'></a>
<center> <h1> POSTme!: Tool for Social Media Messaging Optimization </center>
<center> <h2> Notebook : Named Entity Recognition </h2> </center>
<p style="margin-bottom:1cm;"></p>
<p style="margin-bottom:1cm;"></p>

<div style="background:#EEEDF5;border-top:0.1cm solid #EF475B;border-bottom:0.1cm solid #EF475B;">
    <div style="margin-left: 0.5cm;margin-top: 0.5cm;margin-bottom: 0.5cm;color:#303030">
        <p><strong>Goal:</strong> Named entity recognition (NER) , also known as entity chunking/extraction , is a popular technique used in information extraction to identify and segment the named entities and classify or categorize them under various predefined classes such as person names, organizations, locations, medical codes, time expressions, quantities, monetary values, percentages, etc. This notebook is used to count certin named entities in social media posts </p>

# Install Dependencies

In [ ]:
!pip install contractions
!pip install textsearch
!pip install tqdm

Collecting contractions
  Downloading contractions-0.1.66-py2.py3-none-any.whl (8.0 kB)
Collecting textsearch>=0.0.21
  Downloading textsearch-0.0.21-py2.py3-none-any.whl (7.5 kB)
Collecting pyahocorasick
  Downloading pyahocorasick-1.4.2.tar.gz (321 kB)
     |████████████████████████████████| 321 kB 4.9 MB/s
Collecting anyascii
  Downloading anyascii-0.3.0-py3-none-any.whl (284 kB)
     |████████████████████████████████| 284 kB 39.5 MB/s
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py) ... done
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.2-cp37-cp37m-linux_x86_64.whl size=85448 sha256=9356e51f13c2c1443a7326999b560dd713c0d424b495b462286f2f128416f3ff
  Stored in directory: /root/.cache/pip/wheels/25/19/a6/8f363d9939162782bb8439d886469756271abc01f76fbd790f
Successfully built pyahocorasick
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.0 contractions-0.1.66 pyahocorasick-1.4.2 textsearch-0.0.21
Requirement already satisfied: textsearch in /usr/local/lib/python3.7/dist-packages (0.0.21)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.7/dist-packages (from textsearch) (1.4.2)
Requirement already satisfied: anyascii in /usr/local/lib/python3.7/dist-packages (from textsearch) (0.3.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (4.62.3)

In [ ]:
import nltk
import pandas as pd
import numpy as np

import contractions
import re
import tqdm

from google.colab import drive #to download and upload data directly to google drive

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [ ]:
import spacy
from spacy import displacy

nlp = spacy.load('en_core_web_sm')
from collections import Counter

## Named Entities with spaCY

There are Named Entity Taggers available through popular nlp libraries like "nltk" and "spacy". Each of these libraries follows a different approach to solve the problem. For this task, we use spaCY library. [spaCY](https://spacy.io/api/data-formats#named-entities)

In [ ]:
nlp.pipeline

[('tagger', <spacy.pipeline.pipes.Tagger at 0x7ffb2b6e7e10>),
 ('parser', <spacy.pipeline.pipes.DependencyParser at 0x7ffb2b849360>),
 ('ner', <spacy.pipeline.pipes.EntityRecognizer at 0x7ffb2b8493d0>)]

![](https://i.imgur.com/EEYbJUl.png)

In [ ]:
#first, we calculate many different categories, later we can decide what to include and exclude

pos_family = {
    'person' : ['PERSON'],
    'norp' : ['NORP'],
    'fac' : ['FAC'],
    'org' : ['ORG'],
    'gpe' : ['GPE'],
    'loc' : ['LOC'],
    'product' : ['PRODUCT'],
    'event' : ['EVENT'],
    'work_of_art' : ['WORK_OF_ART'],
    'law' : ['LAW'],
    'language' : ['LANGUAGE'],
    'date' : ['DATE'],
    'time' : ['TIME'],
    'percent' : ['PERCENT'],
    'money' : ['MONEY'],
}

In [ ]:
ner_entities = ['person_count', 'norp_count', 'fac_count', 'organization_count', 'gpe_count', 'loc_count', 'product_count', 'event_count', 'workOfart_count', 'law_count', 'language_count',
                'date_count', 'time_count', 'percent_count', 'money_count']

In [ ]:
#function to count named entities
def check_ner(x, flag):
    cnt = 0
    try:
        nlp_text = nlp(x)
        for tup in [(word.text, word.ent_type_) for word in nlp_text]:
            ppo = list(tup)[1]
            if ppo in pos_family[flag]:
                cnt += 1
    except:
        pass
    return cnt

### Linkedin Data

In [ ]:
df_linkedin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   273 non-null    int64
 1   DateTime                     273 non-null    object
 2   LinkeInPage                  273 non-null    object
 3   DataID                       273 non-null    int64
 4   Tags                         97 non-null     object
 5   PostCampaign                 0 non-null      float64
 6   PostType                     273 non-null    object
 7   PostMessage                  273 non-null    object
 8   Reactions                    273 non-null    int64
 9   Impressions                  273 non-null    int64
 10  Engagement                   273 non-null    float64
 11  Clicks                       273 non-null    int64
 12  Shares                       273 non-null    int64
 13  Comments                     273 non-null    int64
 14  Date                         273 non-null    object
 15  Time                         273 non-null    object
 16  norm_linkedin_posts          268 non-null    object
 17  flesch_reading_ease_score    273 non-null    float64
 18  automated_readability_index  273 non-null    float64
 19  Polarity                     273 non-null    float64
 20  Subjectivity                 273 non-null    float64
dtypes: float64(6), int64(7), object(8)
memory usage: 44.9+ KB

we will use the pre-processed text to count named entities

In [ ]:
feature_col = "norm_linkedin_posts"

In [ ]:
df_linkedin['person_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'person'))

In [ ]:
df_linkedin['norp_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'norp'))

In [ ]:
df_linkedin['fac_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'fac'))

In [ ]:
df_linkedin['organization_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'org'))

In [ ]:
df_linkedin['gpe_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'gpe'))
df_linkedin['loc_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'loc'))
df_linkedin['product_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'product'))
df_linkedin['event_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'event'))
df_linkedin['workOfart_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'work_of_art'))
df_linkedin['law_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'law'))
df_linkedin['language_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'language'))
df_linkedin['date_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'date'))
df_linkedin['time_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'time'))
df_linkedin['percent_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'percent'))
df_linkedin['money_count'] = df_linkedin[feature_col].apply(lambda x: check_ner(x, 'money'))

In [ ]:
df2 = df_linkedin[['person_count', 'norp_count', 'fac_count', 'organization_count', 'gpe_count', 'loc_count', 'product_count', 'event_count', 'workOfart_count', 'law_count', 'language_count',
                'date_count', 'time_count', 'percent_count', 'money_count']]

In [ ]:
df2.head(1)

   person_count  norp_count  fac_count  ...  time_count  percent_count  money_count
0             2           0          0  ...           0              0            0

[1 rows x 15 columns]

In [ ]:
linkedin_ner = df_linkedin[['DataID','person_count', 'norp_count','organization_count', 'gpe_count', 'loc_count', 'product_count',
                'date_count','money_count']]

In [ ]:
linkedin_ner = linkedin_ner.rename(columns={"DataID":"data_id"})

In [ ]:
linkedin_ner.head()

               data_id  person_count  ...  date_count  money_count
0  6622396793785204736             2  ...           1            0
1  6643022712363069440             0  ...           2            0
2  6658384606762418176             2  ...           0            0
3  6669122096871837696             0  ...           3            0
4  6696414383473467392             2  ...           0            0

[5 rows x 9 columns]

In [ ]:
linkedin_ner.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   data_id             273 non-null    int64
 1   person_count        273 non-null    int64
 2   norp_count          273 non-null    int64
 3   organization_count  273 non-null    int64
 4   gpe_count           273 non-null    int64
 5   loc_count           273 non-null    int64
 6   product_count       273 non-null    int64
 7   date_count          273 non-null    int64
 8   money_count         273 non-null    int64
dtypes: int64(9)
memory usage: 19.3 KB

### Twitter Data

In [ ]:
df_twitter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 23 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Unnamed: 0                                   268 non-null    int64
 1   data_id                                      268 non-null    int64
 2   data_text                                    268 non-null    object
 3   data_non_public_metrics_impression_count     268 non-null    int64
 4   data_non_public_metrics_url_link_clicks      210 non-null    float64
 5   data_non_public_metrics_user_profile_clicks  268 non-null    int64
 6   data_organic_metrics_impression_count        268 non-null    int64
 7   data_organic_metrics_like_count              268 non-null    int64
 8   data_organic_metrics_reply_count             268 non-null    int64
 9   data_organic_metrics_retweet_count           268 non-null    int64
 10  data_organic_metrics_url_link_clicks         210 non-null    float64
 11  data_organic_metrics_user_profile_clicks     268 non-null    int64
 12  data_public_metrics_like_count               268 non-null    int64
 13  data_public_metrics_quote_count              268 non-null    int64
 14  data_public_metrics_reply_count              268 non-null    int64
 15  data_public_metrics_retweet_count            268 non-null    int64
 16  data_created_at                              267 non-null    object
 17  data_in_reply_to_user_id                     8 non-null      float64
 18  norm_twitter_posts                           268 non-null    object
 19  flesch_reading_ease_score                    268 non-null    float64
 20  automated_readability_index                  268 non-null    float64
 21  Polarity                                     268 non-null    float64
 22  Subjectivity                                 268 non-null    float64
dtypes: float64(7), int64(13), object(3)
memory usage: 48.3+ KB

In [ ]:
feature_col = "norm_twitter_posts"

In [ ]:
df_twitter['person_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'person'))

In [ ]:
df_twitter['norp_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'norp'))

In [ ]:
df_twitter['fac_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'fac'))

In [ ]:
df_twitter['organization_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'org'))

In [ ]:
df_twitter['gpe_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'gpe'))
df_twitter['loc_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'loc'))
df_twitter['product_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'product'))
df_twitter['event_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'event'))
df_twitter['workOfart_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'work_of_art'))
df_twitter['law_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'law'))
df_twitter['language_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'language'))
df_twitter['date_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'date'))
df_twitter['time_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'time'))
df_twitter['percent_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'percent'))
df_twitter['money_count'] = df_twitter[feature_col].apply(lambda x: check_ner(x, 'money'))

In [ ]:
df = df_twitter[['data_id','person_count', 'norp_count', 'fac_count', 'organization_count', 'gpe_count', 'loc_count', 'product_count', 'event_count', 'workOfart_count', 'law_count', 'language_count',
                'date_count', 'time_count', 'percent_count', 'money_count']]

In [ ]:
df.head()

               data_id  person_count  ...  percent_count  money_count
0  1460472806655893515             0  ...              0            0
1  1457611381902123017             0  ...              0            0
2  1387693344579543040             0  ...              0            0
3  1470619647972196354             0  ...              0            0
4  1420715778689617925             0  ...              0            0

[5 rows x 16 columns]

In [ ]:
twitter_ner = df_twitter[['data_id','person_count', 'norp_count','organization_count', 'gpe_count', 'loc_count', 'product_count',
                'date_count','money_count']]

In [ ]:
twitter_ner.head()

               data_id  person_count  ...  date_count  money_count
0  1460472806655893515             0  ...           0            0
1  1457611381902123017             0  ...           0            0
2  1387693344579543040             0  ...           0            0
3  1470619647972196354             0  ...           0            0
4  1420715778689617925             0  ...           0            0

[5 rows x 9 columns]

In [ ]:
twitter_ner.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   data_id             205 non-null    int64
 1   person_count        205 non-null    int64
 2   norp_count          205 non-null    int64
 3   organization_count  205 non-null    int64
 4   gpe_count           205 non-null    int64
 5   loc_count           205 non-null    int64
 6   product_count       205 non-null    int64
 7   date_count          205 non-null    int64
 8   money_count         205 non-null    int64
dtypes: int64(9)
memory usage: 14.5 KB

## Check and Visualize only 1 TEXT in ROW

In [ ]:
df[df["person_count"]== df["person_count"].max()]

     person_count  norp_count  ...  percent_count  money_count
146             6           0  ...              0            0

[1 rows x 15 columns]

In [ ]:
text_nlp = nlp(df_twitter["post_message"][3])

In [ ]:
text_nlp_pro = nlp(df_twitter["processed_text"][146])

In [ ]:
text_nlp_pro2 = nlp(df_twitter["pro_text2"][3])

In [ ]:
ner_tagged = [(word.text, word.ent_type_) for word in text_nlp]
print(ner_tagged)

[('During', ''), ('menstruation', ''), ('women', ''), ('may', ''), ('require', ''), ('up', ''), ('to', ''), ('DOUBLE', ''), ('the', ''), ('iron', ''), ('in', ''), ('their', ''), ('diet', ''), ('as', ''), ('compared', ''), ('to', ''), ('men', ''), ('.', ''), ('\n\n', ''), ('Learn', ''), ('more', ''), ('at', ''), ('https://t.co/P4irkK3AQG', 'ORG'), ('\n\n', ''), ('#', ''), ('IronDeficiency', 'MONEY'), ('#', 'MONEY'), ('IronDeficiencyDay', 'MONEY'), ('#', 'MONEY'), ('IDD', 'MONEY'), ('#', 'MONEY'), ('IDA', 'MONEY'), ('#', 'MONEY'), ('TakeIronSeriously', ''), ('#', 'MONEY'), ('ListenToYourBody', 'MONEY'), ('#', 'MONEY'), ('Menstruation', ''), ('https://t.co/RaoyXG1PCS', '')]

In [ ]:
x = [(word.ent_type_) for word in text_nlp]
print(x)

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'ORG', '', '', 'MONEY', 'MONEY', 'MONEY', 'MONEY', 'MONEY', 'MONEY', 'MONEY', 'MONEY', '', 'MONEY', 'MONEY', 'MONEY', '', '']

In [ ]:
named_entities = []
temp_entity_name = ''
temp_named_entity = None
for term, tag in ner_tagged:
    if tag:
        temp_entity_name = ' '.join([temp_entity_name, term]).strip()
        temp_named_entity = (temp_entity_name, tag)
    else:
        if temp_named_entity:
            named_entities.append(temp_named_entity)
            temp_entity_name = ''
            temp_named_entity = None

In [ ]:
c = Counter([item[1] for item in named_entities])
c.most_common()

[('MONEY', 2), ('ORG', 1)]

In [ ]:
from spacy import displacy

# visualize named entities
displacy.render(text_nlp, style='ent', jupyter=True)

In [ ]:
displacy.render(text_nlp_pro, style='ent', jupyter=True)

In [ ]:
displacy.render(text_nlp_pro2, style='ent', jupyter=True)